# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3add87d8cdcc8b7ce30f9e3641fb91c74d3850864a01cf2d73af435988c5af2d4dd338ed0e874c406fbd7b7b7efbdda5f49260dfa77f4bab726fc516256a90c8

test:
  secret_key_base: 0ccd8bed5adb937d3525a3fda697ed48383d2c8840c2ae67a8a1984d6225c532d9935494577065db04e0055a89e50f5ccfa08b1093d70342b421746fbffcb685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
